/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ec.vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import java.text.DecimalFormat;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Toshiba
 */
public class Dashboards extends javax.swing.JPanel {

    /**
     * Creates new form Dashboards
     */
    public Dashboards() {
        initComponents();

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rubros = new javax.swing.JLayeredPane();
        RAlimentación = new javax.swing.JPanel();
        REducación = new javax.swing.JPanel();
        btnGraficar = new javax.swing.JButton();

        javax.swing.GroupLayout REducaciónLayout = new javax.swing.GroupLayout(REducación);
        REducación.setLayout(REducaciónLayout);
        REducaciónLayout.setHorizontalGroup(
            REducaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        REducaciónLayout.setVerticalGroup(
            REducaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        btnGraficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ec/vistas/iconos/consultar.png"))); // NOI18N
        btnGraficar.setText("Consultar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RAlimentaciónLayout = new javax.swing.GroupLayout(RAlimentación);
        RAlimentación.setLayout(RAlimentaciónLayout);
        RAlimentaciónLayout.setHorizontalGroup(
            RAlimentaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RAlimentaciónLayout.createSequentialGroup()
                .addGroup(RAlimentaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RAlimentaciónLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnGraficar))
                    .addGroup(RAlimentaciónLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(REducación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        RAlimentaciónLayout.setVerticalGroup(
            RAlimentaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RAlimentaciónLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(REducación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnGraficar)
                .addGap(90, 90, 90))
        );

        Rubros.setLayer(RAlimentación, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout RubrosLayout = new javax.swing.GroupLayout(Rubros);
        Rubros.setLayout(RubrosLayout);
        RubrosLayout.setHorizontalGroup(
            RubrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
            .addGroup(RubrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RAlimentación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RubrosLayout.setVerticalGroup(
            RubrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(RubrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RubrosLayout.createSequentialGroup()
                    .addComponent(RAlimentación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 63, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(Rubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(Rubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        //CONSTRUTES LA INFORMACION PARA PRESENTAR NO ES NECESARIO CLASIFICAR
        //PRIMER PARAMETRO ES LA CANTIDAD
        //EL SEGUNDO EL GRUPO
        //EL TERCERO LA ETIQUETA
        int v = 123;
        DefaultCategoryDataset defaultcategorydataset = new DefaultCategoryDataset();
        defaultcategorydataset.addValue(v, "S1", "Alimentación");
        defaultcategorydataset.addValue(3157D, "S1", "Educación");
        defaultcategorydataset.addValue(1506D, "S1", "Salud");
        defaultcategorydataset.addValue(1283D, "S1", "Vestimenta");
        defaultcategorydataset.addValue(738D, "S1", "Vivienda");

        //creas el objeto freechart
        //TITULO
        //EJE Y
        //EJE X
        JFreeChart jfreechart = ChartFactory.createBarChart("Titulo", "Rubro", "Consumo", defaultcategorydataset, PlotOrientation.HORIZONTAL, false, true, false);
        //		TextTitle texttitle = new TextTitle("Source: Freshmeat (http://www.freshmeat.net/)", new Font("Dialog", 0, 10));
        //		texttitle.setPosition(RectangleEdge.BOTTOM);
        //		jfreechart.addSubtitle(texttitle);
        ChartUtilities.applyCurrentTheme(jfreechart);
        CategoryPlot categoryplot = (CategoryPlot) jfreechart.getPlot();
        categoryplot.setDomainGridlinesVisible(true);
        categoryplot.getDomainAxis().setMaximumCategoryLabelWidthRatio(0.8F);
        NumberAxis numberaxis = (NumberAxis) categoryplot.getRangeAxis();
        numberaxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        BarRenderer barrenderer = (BarRenderer) categoryplot.getRenderer();
        barrenderer.setDrawBarOutline(false);
        StandardCategoryToolTipGenerator standardcategorytooltipgenerator = new StandardCategoryToolTipGenerator("{1}: {2} projects", new DecimalFormat("0"));
        barrenderer.setBaseToolTipGenerator(standardcategorytooltipgenerator);
        GradientPaint gradientpaint = new GradientPaint(0.0F, 0.0F, Color.blue, 0.0F, 0.0F, new Color(0, 0, 64));
        barrenderer.setSeriesPaint(0, gradientpaint);
        //PINTA EN EL JPANEL QUE TENGAS
        ChartPanel myChart = new ChartPanel(jfreechart);
        //        myChart.setMouseWheelEnabled(true);
        REducación.setLayout(new java.awt.BorderLayout());
        REducación.add(myChart, BorderLayout.CENTER);
        REducación.validate();
    }//GEN-LAST:event_btnGraficarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RAlimentación;
    private javax.swing.JPanel REducación;
    private javax.swing.JLayeredPane Rubros;
    private javax.swing.JButton btnGraficar;
    // End of variables declaration//GEN-END:variables
}
